#!/usr/bin/env python

#----------------------------------------------------------------------------
#THE BEER-WARE LICENSE" (Revision 42):
#<tdflowers@gmail.com> wrote this file. As long as you retain this notice you
#can do whatever you want with this stuff. If we meet some day, and you think
#this stuff is worth it, you can buy me a beer in return Tim Flowers
#----------------------------------------------------------------------------

import pysnake
import traceback
import curses

import logging

def main():

  logging.basicConfig(filename='error.log', level=logging.DEBUG)

  try:
    c = pysnake.PySnake()
    c.main_menu()
  except Exception as e:
    logging.debug("got Error: %s" % str(e))
    curses.endwin()
    print(e)
    traceback.print_exc()



if __name__ == '__main__':
  main()
